[package]
name = "bulbdialclock"
version = "1.1.0"
authors = ["Jamie Wilkinson <jaq@spacepants.org>"]
edition = "2021"
license = "GPL-3.0"

[[bin]]
name = "bulbdialclock"
test = false
bench = false

[features]
#default = ["panic-serial"]
panic-serial = ["dep:panic-serial"]
serial-sync = []

[dependencies]
panic-halt = "1.0.0"
panic-serial = { version = "0.1.2", features = [] , optional = true}
ufmt = "0.2.0"
nb = "1.1.0"
embedded-hal = "1.0.0"

[dependencies.arduino-hal]
git = "https://github.com/Rahix/avr-hal"
rev = "ff4909c00ceee76d60f8bd7cc95bc0f3e2ab673f"
features = ["nano168"]

[dependencies.avr-device]
version = "0.7.0"
features = ["atmega168", "rt"]

# Configure the build for minimal size - AVRs have very little program memory
[profile.dev]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "z"
