name: bloat

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  actions: none

jobs:
  cargo_bloat:
    runs-on: ubuntu-latest
    permissions:
      # publish bloat results as a comment
      pull-requests: write
    steps:
      - uses: actions/checkout@master
      - run: sudo apt install avr-libc gcc-avr pkg-config avrdude libudev-dev build-essential
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --verbose
      - uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
